kind: pipeline
type: docker
name: Amd64 Linux Build

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: node:12.18.3
  commands:
  - apt update && apt-get install --no-install-recommends -y gcc-multilib g++-multilib bsdtar rpm libopenjp2-tools
  - npm install
  - npm run dist
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

trigger:
  branch:
  - build1
  event:
  - push
