language: node_js

os:
  - linux
  - osx

node_js: "6.3.0"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi

script:
  - npm test

notifications:
  email:
    on_success: never
on_failure: change
