language: node_js

os:
  - linux
  - osx

node_js: "12.4.0"

services:
  - xvfb

script:
  - npm install -g istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha

notifications:
  email:
    on_success: never

on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)
