name: macOS build

on:
  push:
    branches:
      - release
      - snap
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'
    - run: npm install -g npm
    - run: npm install
    - run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.github_token }}
